name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build Go project
        run: |
          go build -o wip 

      - name: Set up GitHub CLI
        uses: docker://ghcr.io/github/cli/cli:latest

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes "Release for version ${{ github.ref_name }}" \
            wip 
